#!/usr/bin/env python3
"""check-map.py is built from two packages, reproducibly, and a stale build is caught (#74).

The checker is written as modules and shipped as one file (0015), so there are two artefacts
that must not drift: the modules a person edits and the file a package carries and the factory
imports. Since 0032 the modules span two packages -- `mapcontract`, which says what a map's
fields mean, and `mapvalidator`, which checks them -- and the built file is still one file, so the
join is what keeps a boundary in the sources from becoming a boundary in the artefact. These
tests hold the build to three claims:

  * the committed check-map.py is exactly what the committed modules build, and building again,
    from a copy somewhere else, gives the same bytes;
  * `--check` fails on a module changed without rebuilding and on a built file edited by hand,
    and the build refuses sources whose join would not mean what the package means;
  * the package and the built file give the same output and exit code on every example map.

The checks themselves are proved in test_check_map.py, against the built file.

Run: python3 -m unittest discover -s tools/tests
"""
import glob
import importlib
import importlib.util
import io
import os
import shutil
import sys
import tempfile
import unittest
from contextlib import redirect_stdout, redirect_stderr

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
REPO = os.path.dirname(TOOLS)
BUILT = os.path.join(TOOLS, "check-map.py")
SOURCES = TOOLS  # the directory the packages live in, as --sources means it

_spec = importlib.util.spec_from_file_location("build_check_map", os.path.join(TOOLS, "build-check-map.py"))
builder = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(builder)


def read(path):
    with open(path, "rb") as handle:
        return handle.read()


def run(main, argv):
    out, err = io.StringIO(), io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        code = main(argv)
    return code, out.getvalue(), err.getvalue()


class BuildCase(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.tmp, True)
        self.sources = os.path.join(self.tmp, "somewhere", "else")
        for package in builder.PACKAGES:
            shutil.copytree(os.path.join(SOURCES, package), os.path.join(self.sources, package),
                            ignore=shutil.ignore_patterns("__pycache__"))
        self.target = os.path.join(self.tmp, "check-map.py")
        shutil.copy(BUILT, self.target)

    def edit(self, module, old, new):
        """`module` is dotted, as MODULES names it."""
        path = os.path.join(self.sources, *module.split(".")) + ".py"
        text = read(path).decode("utf-8")
        self.assertIn(old, text)
        with open(path, "wb") as handle:
            handle.write(text.replace(old, new, 1).encode("utf-8"))

    def check(self):
        return run(builder.main, ["--check", "--sources", self.sources, "--target", self.target])


class TestReproducible(BuildCase):
    def test_the_committed_file_is_what_the_committed_modules_build(self):
        code, out, err = run(builder.main, ["--check"])
        self.assertEqual(code, 0, err)
        self.assertEqual(builder.build(), read(BUILT))

    def test_a_copy_elsewhere_builds_the_same_bytes_twice(self):
        first, second = builder.build(self.sources), builder.build(self.sources)
        self.assertEqual(first, second)
        self.assertEqual(first, read(BUILT))

    def test_the_built_file_says_it_is_generated_and_from_what(self):
        head = read(BUILT).decode("utf-8").split("\n")[:3]
        self.assertEqual(head[0], "#!/usr/bin/env python3")
        self.assertIn("GENERATED by tools/build-check-map.py from tools/mapcontract/ "
                      "and tools/mapvalidator/", head[1])

    def test_every_module_is_joined_and_none_is_large(self):
        """A module in a joined package and not in MODULES is one the shipped file does not
        carry, which is how a check could exist in the package and not in a map's copy."""
        on_disk = {f"{package}.{os.path.splitext(name)[0]}"
                   for package in builder.PACKAGES
                   for name in os.listdir(os.path.join(SOURCES, package)) if name.endswith(".py")}
        inits = {f"{package}.__init__" for package in builder.PACKAGES}
        self.assertEqual(on_disk, set(builder.MODULES) | inits)
        for name in builder.MODULES:
            lines = read(os.path.join(SOURCES, *name.split(".")) + ".py").count(b"\n")
            self.assertLessEqual(lines, 300, f"{name} is {lines} lines")


class TestStale(BuildCase):
    def test_a_module_changed_without_rebuilding_is_stale(self):
        self.edit("mapvalidator.status", "names no test that proves", "names no test proving")
        code, _, err = self.check()
        self.assertEqual(code, 1, err)
        self.assertIn("is stale", err)
        self.assertEqual(read(self.target), read(BUILT), "--check wrote the target")

        code, _, err = run(builder.main, ["--sources", self.sources, "--target", self.target])
        self.assertEqual(code, 0, err)
        self.assertIn(b"names no test proving", read(self.target))
        self.assertEqual(self.check()[0], 0)

    def test_a_built_file_edited_by_hand_is_stale(self):
        with open(self.target, "ab") as handle:
            handle.write(b"# a local fix\n")
        code, _, err = self.check()
        self.assertEqual(code, 1, err)
        self.assertIn("is stale", err)

    def test_a_missing_built_file_is_stale(self):
        os.remove(self.target)
        code, _, err = self.check()
        self.assertEqual(code, 1, err)
        self.assertIn("does not exist", err)


class TestRefused(BuildCase):
    def assert_refused(self, *expected):
        code, _, err = self.check()
        self.assertEqual(code, 1, err)
        self.assertIn("refused:", err)
        for text in expected:
            self.assertIn(text, err)
        self.assertEqual(read(self.target), read(BUILT), "a refused build wrote the target")

    def test_a_third_party_import(self):
        self.edit("mapcontract.entry", '"""\n', '"""\nimport yaml\n')
        self.assert_refused("mapcontract/entry.py", "only the standard library")

    def test_an_aliased_import(self):
        self.edit("mapvalidator.relations", "import sys\n", "import sys as system\n")
        self.assert_refused("mapvalidator/relations.py", "without aliases")

    def test_an_import_from_a_later_module(self):
        self.edit("mapvalidator.diagnostics", '"""\n', '"""\nfrom .cli import main\n')
        self.assert_refused("mapvalidator/diagnostics.py", "earlier in MODULES")

    def test_an_import_from_a_later_package(self):
        """The contract is joined first, so it cannot read a check even by its package name."""
        self.edit("mapcontract.entry", '"""\n', '"""\nfrom mapvalidator.diagnostics import verdict\n')
        self.assert_refused("mapcontract/entry.py", "earlier in MODULES")

    def test_a_package_import_of_a_name_the_module_does_not_define(self):
        self.edit("mapvalidator.status", "from mapcontract.vocabulary import ID_LIST_FIELDS\n",
                  "from mapcontract.vocabulary import ID_LIST_FIELDS, entries_of\n")
        self.assert_refused("mapvalidator/status.py", "`entries_of` is not a top-level name",
                            "mapcontract/vocabulary.py")

    def test_an_import_below_the_top(self):
        self.edit("mapvalidator.cli", "def find_manifest(map_path):\n",
                  "def find_manifest(map_path):\n    import glob\n")
        self.assert_refused("mapvalidator/cli.py", "below the top")

    def test_a_name_two_modules_define(self):
        """Across packages as well as within one: the built file has one namespace."""
        self.edit("mapvalidator.status", "def tests_problems(",
                  "def label(position):\n    return position\n\n\ndef tests_problems(")
        self.assert_refused("mapvalidator/status.py", "`label`", "mapcontract/entry.py defines too")

    def test_a_name_read_but_never_imported(self):
        self.edit("mapvalidator.crossrefs",
                  "from mapcontract.entry import block, corpora_of, entries_of, index, label\n",
                  "from mapcontract.entry import block, corpora_of, entries_of, index\n")
        self.assert_refused("mapvalidator/crossrefs.py", "reads label")

    def test_a_package_init_that_holds_code(self):
        self.edit("mapcontract.__init__", '"""\n', '"""\nWIDTH = 96\n')
        self.assert_refused("mapcontract/__init__.py", "holds code")


class TestPackageAgreesWithBuild(unittest.TestCase):
    """The modules are a real package, not fragments that only work once joined."""

    @classmethod
    def setUpClass(cls):
        sys.path.insert(0, TOOLS)
        try:
            cls.package = importlib.import_module("mapvalidator.cli")
            cls.phases = importlib.import_module("mapvalidator.phases")
            cls.vocabulary = importlib.import_module("mapcontract.vocabulary")
        finally:
            sys.path.remove(TOOLS)
        spec = importlib.util.spec_from_file_location("check_map_built", BUILT)
        cls.built = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(cls.built)

    def test_the_same_checks_and_schema_versions(self):
        self.assertEqual([n for n, _ in self.phases.CHECKS], [n for n, _ in self.built.CHECKS])
        self.assertEqual(self.phases.STATUS_DEPENDENT, self.built.STATUS_DEPENDENT)
        self.assertEqual(self.vocabulary.SCHEMA_VERSIONS, self.built.SCHEMA_VERSIONS)

    def test_the_same_verdicts_on_every_example_map(self):
        maps = sorted(glob.glob(os.path.join(REPO, "examples", "*", "corpus-map*.json")))
        self.assertTrue(maps, "no example maps -- this test proved nothing")
        for path in maps:
            for extra in ([], ["--phase", "consumer"], ["--verbose"]):
                with self.subTest(map=os.path.relpath(path, REPO), argv=extra):
                    self.assertEqual(run(self.package.main, [path, *extra]),
                                     run(self.built.main, [path, *extra]))


if __name__ == "__main__":
    unittest.main()
