#!/usr/bin/env python3
"""Build tools/check-map.py from the modules in tools/mapcontract/ and tools/mapvalidator/ (#74).

A map package ships the checker as one standard-library file (0015), and the factory imports
that same file (0016). The single file is a distribution format, not a way to write a checker,
so the checker is written as modules and this script joins them. The join is textual and
deterministic: the package docstring, the union of the modules' standard-library imports, then
each module's body in MODULES order under a comment naming the module it came from. The output
depends on the modules' bytes and nothing else -- no timestamp, no path, no digest of itself --
so the same sources build the same bytes on any machine, and `--check` can compare.

It joins two packages, because the checker is one of three subsystems and not the owner of the
map's vocabulary: `mapcontract` holds what a map's fields mean, and `mapvalidator` holds the checks
(0032). The shipped file is still one file, so the boundary the packages draw is a boundary in
the sources and not in the artefact -- which is the whole reason the join has rules.

Joining modules into one namespace is only safe under rules, and the build refuses sources that
break them rather than emitting a file that would behave differently from the package:

  * every import is at the top of a module, after its docstring;
  * a package import names a module earlier in MODULES and names it defines at top level --
    `from .module import name, ...` within a package, `from package.module import name, ...`
    across one -- and no `import .module`, no aliases, no `*`;
  * every other import is from the standard library, without an alias;
  * no top-level name is defined by two modules, or by a module and an import;
  * every global name a module reads is a builtin, its own, or one it imports, so a module
    that only works because the joined file happens to define the name is caught here.

What it cannot do: prove the package and the built file behave the same. The rules above make
the join a renaming-free concatenation, and `test_build_check_map.py` runs both on the example
maps; nothing stronger is claimed.

Usage: build-check-map.py [--check] [--sources DIR] [--target FILE]
--sources is the directory the packages live in, `tools/` by default, not one package.
Exit 0 when the target was written or is already current; 1 with --check when it is stale, or
when the sources break a rule above; 2 on a usage error.
"""
import argparse
import ast
import builtins
import os
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
SOURCES = TOOLS
TARGET = os.path.join(TOOLS, "check-map.py")

# The modules, dotted, in the order the built file holds them. A module imports only from
# modules before it, which the build checks, so this order is also a valid definition order.
# The contract comes first because both packages' checks read it and it reads nothing.
MODULES = ("mapcontract.vocabulary", "mapcontract.entry",
           "mapvalidator.diagnostics", "mapvalidator.schema", "mapvalidator.extent",
           "mapvalidator.relations", "mapvalidator.manifest", "mapvalidator.extraction",
           "mapvalidator.ambiguity", "mapvalidator.bounds", "mapvalidator.status",
           "mapvalidator.inputs", "mapvalidator.crossrefs", "mapvalidator.correspondence",
           "mapvalidator.phases", "mapvalidator.cli")

# The packages MODULES spans, in first-appearance order, and the one whose `__init__.py` is the
# built file's docstring. Every package's `__init__.py` must be a docstring and nothing else;
# only this one's is used, because the built file is the checker and describes itself as one.
PACKAGES = tuple(dict.fromkeys(name.split(".")[0] for name in MODULES))
DOCSTRING_FROM = "mapvalidator"


def _path_of(name):
    """A module's path relative to --sources, as a path rather than a dotted name, for messages
    and section comments: the reader is going to open a file."""
    return os.path.join(*name.split(".")) + ".py"

HEADER = """#!/usr/bin/env python3
# GENERATED by tools/build-check-map.py from tools/mapcontract/ and tools/mapvalidator/ -- do not edit this file.
# Edit the modules there and run the build; scripts/validate.sh fails while this file is stale.
# It is one standard-library-only file because a map package ships it (0015).
"""
RULE_WIDTH = 96


class Refused(Exception):
    """The sources break a rule the join depends on."""


def _docstring_node(tree, where):
    first = tree.body[0] if tree.body else None
    if not (isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant)
            and isinstance(first.value.value, str)):
        raise Refused(f"{where} does not open with a docstring stating its responsibility")
    return first


def _top_level_names(tree):
    names = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, (ast.Assign, ast.AnnAssign, ast.AugAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for target in targets:
                names.update(n.id for n in ast.walk(target) if isinstance(n, ast.Name))
    return names


def _bound_anywhere(tree):
    """Every name the module binds at any depth. Generous on purpose: it only has to catch a
    global read that nothing in the module could have bound."""
    bound = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and not isinstance(node.ctx, ast.Load):
            bound.add(node.id)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            bound.add(node.name)
        elif isinstance(node, ast.arg):
            bound.add(node.arg)
        elif isinstance(node, ast.ExceptHandler) and node.name:
            bound.add(node.name)
    return bound


def _parse(sources, name):
    path = os.path.join(sources, _path_of(name))
    try:
        with open(path, "rb") as handle:
            text = handle.read().decode("utf-8")
    except (OSError, UnicodeDecodeError) as error:
        raise Refused(f"cannot read {path}: {error}")
    if "\r" in text:
        raise Refused(f"{_path_of(name)} has carriage returns; the build is defined over LF sources")
    try:
        return text, ast.parse(text, filename=path)
    except SyntaxError as error:
        raise Refused(f"{_path_of(name)} does not parse: {error}")


def build(sources=SOURCES):
    """The built file's bytes, or Refused naming the rule the sources break."""
    docstring = None
    for package in PACKAGES:
        init_text, init_tree = _parse(sources, package + ".__init__")
        where = _path_of(package + ".__init__")
        doc = _docstring_node(init_tree, where)
        if len(init_tree.body) != 1:
            raise Refused(f"{where} holds code; a package's __init__.py states what the package "
                          f"owns and nothing else")
        if package == DOCSTRING_FROM:
            lines = init_text.split("\n")
            docstring = "\n".join(lines[doc.lineno - 1:doc.end_lineno])
    if docstring is None:
        raise Refused(f"DOCSTRING_FROM names {DOCSTRING_FROM!r}, which no module in MODULES is in")

    stdlib_imports, sections, defined = set(), [], {}
    for position, name in enumerate(MODULES):
        text, tree = _parse(sources, name)
        where, package = _path_of(name), name.split(".")[0]
        _docstring_node(tree, where)
        body_start, imported = 1, set()
        for node in tree.body[1:]:
            if not isinstance(node, (ast.Import, ast.ImportFrom)):
                break
            body_start += 1
            # A package import, written either way: `from .module` inside a package, or
            # `from package.module` across one. Both name one module, and it must be earlier.
            target = None
            if isinstance(node, ast.ImportFrom) and node.level == 1 and node.module:
                target = f"{package}.{node.module}"
            elif (isinstance(node, ast.ImportFrom) and not node.level and node.module
                    and node.module.split(".")[0] in PACKAGES):
                target = node.module
            if target is not None or (isinstance(node, ast.ImportFrom) and node.level):
                if target not in MODULES[:position]:
                    written = ("." * node.level) + (node.module or "")
                    raise Refused(f"{where}:{node.lineno}: imports from {written}; "
                                  f"a package import names a module earlier in MODULES")
                for alias in node.names:
                    if alias.asname or alias.name == "*" or alias.name not in defined.get(target, set()):
                        raise Refused(f"{where}:{node.lineno}: `{alias.name}` is not a top-level name "
                                      f"{_path_of(target)} defines, imported without an alias")
                    imported.add(alias.name)
                continue
            for alias in node.names:
                root = (node.module if isinstance(node, ast.ImportFrom) else alias.name).split(".")[0]
                if root not in sys.stdlib_module_names or alias.asname or alias.name == "*":
                    raise Refused(f"{where}:{node.lineno}: imports {ast.unparse(node)!r}; the shipped "
                                  f"checker imports only the standard library, without aliases")
                imported.add(alias.name.split(".")[0])
            if isinstance(node, ast.Import):
                stdlib_imports.update(f"import {alias.name}" for alias in node.names)
            else:
                stdlib_imports.update(f"from {node.module} import {alias.name}" for alias in node.names)
        for node in tree.body[body_start:]:
            for inner in ast.walk(node):
                if isinstance(inner, (ast.Import, ast.ImportFrom)):
                    raise Refused(f"{where}:{inner.lineno}: an import below the top of the module "
                                  f"cannot be hoisted into the built file")

        own = _top_level_names(tree)
        everyone = set().union(*defined.values()) if defined else set()
        for clash in sorted(own & everyone):
            owner = next(m for m, names in defined.items() if clash in names)
            raise Refused(f"{where}: defines `{clash}`, which {_path_of(owner)} defines too; the "
                          f"built file has one namespace")
        defined[name] = own
        read = {n.id for n in ast.walk(tree) if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Load)}
        unbound = read - own - imported - _bound_anywhere(tree) - set(dir(builtins))
        if unbound:
            raise Refused(f"{where}: reads {', '.join(sorted(unbound))} without defining or importing it")

        start = tree.body[body_start - 1].end_lineno  # the line after the docstring or last import
        body = "\n".join(text.split("\n")[start:]).strip("\n")
        if not body:
            raise Refused(f"{where} has no body")
        comment = [("# " + line).rstrip() for line in ast.get_docstring(tree).split("\n")]
        rule = f"# --- tools/{_path_of(name).replace(os.sep, '/')} "
        sections.append("\n".join([rule + "-" * max(3, RULE_WIDTH - len(rule))] + comment) + "\n\n\n" + body)

    names = [n for n in (s.split()[-1] for s in stdlib_imports)]
    for clash in sorted({n for n in names if names.count(n) > 1} | (set(names) & set().union(*defined.values()))):
        raise Refused(f"`{clash}` is both imported and defined, or imported twice under one name")
    plain = sorted(s for s in stdlib_imports if s.startswith("import "))
    froms = sorted(s for s in stdlib_imports if s.startswith("from "))
    imports = "\n".join(plain + froms)
    text = HEADER + docstring + "\n" + imports + "\n\n\n" + "\n\n\n".join(sections) + "\n"
    return text.encode("utf-8")


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Build tools/check-map.py from tools/mapcontract/ and tools/mapvalidator/.")
    parser.add_argument("--check", action="store_true",
                        help="write nothing; exit 1 if the target is not what the sources build")
    parser.add_argument("--sources", default=SOURCES,
                        help="the directory the packages live in (default tools/)")
    parser.add_argument("--target", default=TARGET, help="the built file (default tools/check-map.py)")
    args = parser.parse_args(argv)
    missing = [p for p in PACKAGES if not os.path.isdir(os.path.join(args.sources, p))]
    if missing:
        print(f"{args.sources} holds no {', '.join(missing)} package", file=sys.stderr)
        return 2

    try:
        built = build(args.sources)
    except Refused as error:
        print(f"refused: {error}", file=sys.stderr)
        return 1
    try:
        with open(args.target, "rb") as handle:
            current = handle.read()
    except FileNotFoundError:
        current = None
    except OSError as error:
        print(f"cannot read {args.target}: {error}", file=sys.stderr)
        return 2

    size = f"{len(MODULES)} modules, {len(built.splitlines())} lines"
    if current == built:
        print(f"{args.target} is current: {size}")
        return 0
    if args.check:
        if current is None:
            print(f"{args.target} does not exist; run tools/build-check-map.py", file=sys.stderr)
            return 1
        have, want = current.decode("utf-8", "replace").split("\n"), built.decode("utf-8").split("\n")
        line = next((i for i, (a, b) in enumerate(zip(have, want)) if a != b), min(len(have), len(want)))
        print(f"{args.target} is stale: it is not what the joined packages build (first difference at "
              f"line {line + 1}). Edit the modules, not the built file, and run tools/build-check-map.py",
              file=sys.stderr)
        return 1
    with open(args.target, "wb") as handle:
        handle.write(built)
    os.chmod(args.target, 0o755)
    print(f"wrote {args.target}: {size}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
